#server:
#  port: 80

spring:
  application:
    name: aichat

  profiles:
    active: dev # 默认为开发环境

  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 300MB #限制文件上传大小为300M
      max-request-size: 300MB

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

#jwt:
#  tokenHeader: Authorization #JWT存储的请求头
#  secret: mall-admin-secret #JWT加解密使用的密钥
#  expiration: 604800 #JWT的超期限时间(60*60*24*7)
#  tokenHead: 'Bearer '  #JWT负载中拿到开头